### ISSUE TITLE
Typos & Grammar

### ISSUE THREAD

**Issue by dushr** [mamachanko/import-lymph#34]
> - README.md: Introduction
>   We will not discuss the differences between the two. We won't talk about how services might **~~safe~~** **save** your development teams or your business. Neither will we talk about sophisticated networking topologies, Docker, "microservices", ...
> - README.md: The greeting service
>   the response was once **~~more~~** **again** serialized(MessagePack) and sent back(ZeroMQ) to the requestee
> - README.md: The listen service
>   It simply prints the greeted name contained in the event's body. Everytime an event of this type occurs exactly **~~once~~** **one** instance of the listen service will consume it.
> - README.md: The listen service
>   Keep in mind that if another service would've subscribed to this event as well, **~~once~~** **one** instance of it would've also consumed the event.
> - README.md: The listen service
>   If we were to run several instances of the listen services, each event would be consumed by exactly **~~once~~** **one** instance. However, lymph allows to broadcast events as mentioned above.

**Comment by mamachanko** [comment]
@dushyant88 thanks! on it.
